Update feature-udp.md
outsideris/http3-explained pull request #10
Opened 2019-02-09 06:17 UTC by jukkume

Hello
I've made some changes to make the text look more natural.

Please let me know if there are any additional repository management guidelines I should follow.
Thank you.

2019-02-12 05:00 UTC, outsideris requested changes
전체 문서를 평문으로 쓰고 있는데 올려주신 변경은 문체가 존재말로 되어 있어서 맞춰주시면 감사하겠습니다.

2019-02-12 05:00 UTC, outsideris commented on ko/feature-udp.md
> +당신이 우연히 네트워크 트래픽을 보게 된다면 QUIC이 UDP 패킷으로 나타나는 것을 볼 수 있습니다.
`당신이`는 필요없는 부분 같습니다.

2019-02-12 22:25 UTC, jukkume commented on ko/feature-udp.md
> +당신이 우연히 네트워크 트래픽을 보게 된다면 QUIC이 UDP 패킷으로 나타나는 것을 볼 수 있습니다.
리뷰 감사합니다.
피드백 주신사항 아래 위치에 수정하여 반영하였습니다 - https://github.com/outsideris/http3-explained/pull/10/commits/c5cf65f32f00c41ff54472926d5315fffa4d4b5c#diff-be556083ca3bd08600c452ac2f9830cdL17

2019-02-12 22:26 UTC, jukkume commented
리뷰 감사합니다.
피드백 주신사항 수정하여 반영하였습니다 - c5cf65f

2019-02-15 00:01 UTC, keesun commented
@jukkume 님 혹시 한글만 보고 다듬고 계신가요? #14 제가 보낸 풀리퀘랑 겹치는데 저는 원문하고 비교하면서 교정을 했습니다. 혹시 제 PR을 리뷰 해주시면 제가 반영할께요.

2019-02-15 08:00 UTC, jukkume commented
@keesun 
영어와 같이 보면서 다듬어 보았습니다.
다만, 의미가 전달되는데 오류가 없다면 원문을 그대로 따라가지는 않고 약간 수정하여서 작성하는 방식의 수정도 일부 진행하였습니다.

오타 부분만 수정된다면 #14 부분의 수정사항에 대한 이견 없습니다.

2019-02-21 02:09 UTC, outsideris commented
컨플릭트 확인 부탁드립니다. #14 를 머지해서 발생한 충돌입니다.

2019-02-22 15:13 UTC, outsideris commented
한국어 번역을 원 저장소에 머지했습니다. 이 PR이 열려있는데 머지를 해버려서 죄송하지만 원 저장소의 푸시 권한을 받게 되어 수정하실 내용이 있으면 원 저장소에 PR을 올리시고 머지하는게 기여하신 크레딧을 남기는데도 좋겠다고 생각했습니다. 일단 이 PR을 닫겠습니다.

2019-02-22 15:13 UTC, closed without merging

2019-02-22 15:35 UTC, jukkume commented
@outsideris 
넵 감사합니다