Update feature-reliable.md
outsideris/http3-explained pull request #8
Opened 2019-02-09 05:45 UTC by jukkume

Hello
I've made some changes to make the text look more natural.

Please let me know if there are any additional repository management guidelines I should follow.
Thank you.

2019-02-12 04:59 UTC, outsideris requested changes
전체 문서를 평문으로 쓰고 있는데 올려주신 변경은 문체가 존재말로 되어 있어서 맞춰주시면 감사하겠습니다.

2019-02-12 04:59 UTC, outsideris commented on ko/feature-reliable.md
> +UDP 프로토콜은 데이터 전송의 신뢰성을 보장하지 않지만, QUIC 은 UDP 프로토콜 위에 새로운 계층을 추가함으로써 신뢰성을 제공합니다.
UDP에 꼭 프로토콜이라고 붙여주어야 하는지 모르겠습니다.
`QUIC 은`-> `QUIC은`

2019-02-12 04:59 UTC, outsideris commented on ko/feature-reliable.md
> +한 엔드포인트로부터 QUIC 프로토콜을 통해 전송된 데이터는 연결이 유지되는 한 다른 엔드포인에서 수신할 수 있습니다.
여기도 꼭 프로토콜이라고 붙여줘야하는지 고민되네요.

2019-02-12 22:31 UTC, jukkume commented
리뷰 감사합니다.
피드백 주신사항 수정하여 반영하였습니다 - 895f932

2019-02-15 03:46 UTC, outsideris approved these changes

2019-02-15 03:47 UTC, merged